# Generated by Django 3.2.8 on 2021-10-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
